### ISSUE TITLE
Add CSS class 'FTF' to link flair

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#10]
Sorry, I forgot to mention this before. The 'Fresh Topic Friday' flair in CMV also needs the CSS class 'FTF' to look like it usually does.

**Comment by perezdev** [comment]
That's probably why it's spamming that guy. The default FTF text is "Fresh Topic Friday."

![image](https://user-images.githubusercontent.com/3408775/36301206-a4ca6dda-12c9-11e8-8731-aff8fbc870be.png)

You can change it in the config. The bot uses the flair to determine that the user has already been PMed since there's no database.

**Comment by Snorrrlax** [comment]
'Flair Text' is correct. The CSS class is separate:

![ftfflair](https://user-images.githubusercontent.com/4283937/36301389-8a024b0c-12fc-11e8-932e-870b09707330.png)

**Comment by perezdev** [comment]
Ah. Okay. So then I don't understand the issue. Can you elaborate on what you mean when you say, "CMV also needs the CSS class 'FTF' to look like it usually does."

**Comment by Snorrrlax** [comment]
Here are two posts - the top one has the CSS class 'FTF', and the second one was flaired by CMVModBot:

![ftfflair2](https://user-images.githubusercontent.com/4283937/36303454-1a00a832-1304-11e8-88d2-83f39ab2eb81.png)

The CSS class makes it green and changes position. Here's a snippet from our custom stylesheet:

`.linkflair-FTF .buttons:after { content: 'FRESH TOPIC FRIDAY'; background: #66BB6A; }`

**Comment by perezdev** [comment]
Ah. So I'm guessing that CSS is case sensitive. Since this is configurable, I updated the wiki config file to match.

![image](https://user-images.githubusercontent.com/3408775/36567387-e3250730-17eb-11e8-8e9d-85cbbe1d274d.png)

**Comment by Snorrrlax** [comment]
Actually, I don't believe it is. The capital letters you see in that snippet of code are just how the CSS is stylised. The actual flair text is just 'Fresh Topic Friday', with a CSS class of 'FTF'.

**Comment by Snorrrlax** [comment]
Ah, I just realised something. Is CMVModBot essentially writing a new flair each time, hence its inability to add CSS class?

Could we have the bot choose from the current list of link flair options instead? The correct 'Fresh Topic Friday' one is in there.

**Comment by perezdev** [comment]
Reddit doesn't provide a way to set a flair from a list. You just give it the name of the flair, and if it matches to what you already setup, it gets shown. So it's only showing up because it's writing the correct name.

Can you apply the flair to the test sub and I'll look into why it's messing up?

**Comment by Snorrrlax** [comment]
Done. I flaired your stickied post.

**Comment by perezdev** [comment]
I'm a dummy. I meant the CSS, so I test why the flair being set by the bot doesn't showing the CSS correctly. It doesn't have to be right now.

**Comment by Snorrrlax** [comment]
I added the relevant bit of CSS to the test sub too, though.

**Comment by perezdev** [comment]
Ah, Okay. Thanks

**Comment by Snorrrlax** [comment]
You can see the green 'Fresh Topic Friday' flair on r/CMVModBotTest, only applied to your top post.

**Comment by Snorrrlax** [comment]
I think we can close this.
