### ISSUE TITLE
The bot missed this Rule E violation

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#12]
This post: https://www.reddit.com/r/changemyview/comments/7ydzbz/cmv_the_wilson_effect_definitively_proves_that/

It was made at 12:36 UTC, but withheld due to OP's low karma, and I approved it at 12:48 UTC. 

6 hours later, the bot still hadn't removed it despite there being zero replies from OP.

**Comment by perezdev** [comment]
This is most likely fixed with 88dbfad2fd3ca25c6e00bf1ef382ebb33481086d. Closing for now. Please open new issue if it happens again.
