### ISSUE TITLE
The bot removed my mod post for Rule E

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#23]
https://www.reddit.com/r/changemyview/comments/82syo0/mod_post_we_are_recruiting_new_moderators/

**Comment by Snorrrlax** [comment]
It keeps happening even though I've responded to a comment.

**Comment by Snorrrlax** [comment]
Just realised "exclude mods" was set to false in the config. I've changed that now. Does it need to be made the default option though?

**Comment by perezdev** [comment]
I set the Rule E to exclude mods by default  0589917
