### ISSUE TITLE
A few minor changes to ModBot's comments

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#7]
[Rule E Removal comment](https://www.reddit.com/r/CMVModBotTest/comments/7ws7ye/cmv_this_is_another_test/du2rq1h/).

Changes are: "u/" before username, "removed" instead of "remove", space between ">" and text, new paragraph for appeal line, correct link for "message the mods", and include "message the" in link text:

---

Sorry, u/Snorrrlax - your submission has been removed for breaking rule E:

> Only post if you are willing to have a conversation with those who reply to you, and are available to start doing so within 3 hours of posting. If you haven't replied within this time, your post will be removed. [See the wiki for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_e). 

If you would like to appeal, please respond substantially to some of the arguments people have made, and then [message the moderators by clicking this link](https://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview).

---

[Rule E Restriction comment](https://www.reddit.com/r/CMVModBotTest/comments/7x8bba/cmv_this_is_a_final_test/du68ydv/).

Changes are: "u/" before username, "your" instead of "Your", "see the wiki" link instead of "more info here", "a new post" instead of "your new post", "must first" instead of "first must", bolding of sentence, "previous one" instead of "previous post", added line after bolding, "questions or concerns" instead of "problems or special circumstances", and removing the "automated bot" line at the end.

---

Sorry, u/Snorrrlax - your post to CMV has been removed due to a [previous post](https://www.reddit.com/r/CMVModBotTest/comments/7ws7ye/cmv_this_is_another_test/) of yours breaking Rule E. This is a fundamental rule, as CMV is all about having a conversation. [See the wiki for more information](http://www.reddit.com/r/changemyview/wiki/rules#wiki_rule_e).

If you wish to continue with a new post, you must first **respond to some comments in your previous one, and then resubmit**. CMVModBot will make sure a reasonable effort has been made before approving the resubmission. 

Please [message the moderators](https://www.reddit.com/message/compose?to=%2Fr%2Fchangemyview) if you have any questions or concerns.

---

**Comment by perezdev** [comment]
Completed changes on commit 3fa3e5388442f2d5b189f7043634ab5a5305fbf8
